REMOVE SOCIAL AUTH (comments code, so it's easier to revert)
This is causing problems:

    django.db.utils.OperationalError: no such table: social_auth_usersocialauth